import {atom, useAtomValue} from "jotai";
import getAutoStepType from "../../utils/getAutoStepType.ts";
import {autoDataAtom} from "../AutoData/useAutoData.ts";

export const outputCodeAtom = atom((get) => {
    const autoData = get(autoDataAtom);

    // Iterate through the auto steps and generate code for each one, then join them with newlines
    const codeLines = autoData.steps.map(step => {
        const autoStepType = getAutoStepType(step);
        if (!autoStepType)
            return `// Unknown step type: ${step.typeID}`;
        return autoStepType.generateCode(step);
    });

    // Add a code prefix with includes and function definition
    const CODE_PREFIX = `
// =====================================
//     ${autoData.name}
//     Generated by AutoDevil ${APP_VERSION}
//     https://auto.devilbots.org/
// =====================================

AutoBuilder autoBuilder;
`;

    const CODE_SUFFIX = `

// =====================================
//     End of ${autoData.name}
// =====================================
    `;

    return CODE_PREFIX + codeLines.join("\n") + CODE_SUFFIX;
});

export default function useOutputCode() {
    return useAtomValue(outputCodeAtom);
}