import {atom, useAtomValue} from "jotai";
import {autoStepsAtom} from "../AutoData/useAutoSteps.ts";
import getAutoStepType from "../../utils/getAutoStepType.ts";

export const outputCodeAtom = atom((get) => {
    const autoSteps = get(autoStepsAtom);

    // Iterate through the auto steps and generate code for each one, then join them with newlines
    const codeLines = autoSteps.map(step => {
        const autoStepType = getAutoStepType(step);
        if (!autoStepType)
            return `// Unknown step type: ${step.typeID}`;
        return autoStepType.generateCode(step);
    });

    // Add a code prefix with includes and function definition
    const CODE_PREFIX = `
// =====================================
//     Generated by AutoDevil ${APP_VERSION}
//     https://auto.devilbots.org/
// =====================================

AutoBuilder autoBuilder;
`;

    const CODE_SUFFIX = `
    `;

    return CODE_PREFIX + codeLines.join("\n") + CODE_SUFFIX;
});

export default function useOutputCode() {
    return useAtomValue(outputCodeAtom);
}